services:
  db:
    image: postgres:15
    container_name: llum_db
    restart: always
    environment:
      POSTGRES_USER: llum
      POSTGRES_PASSWORD: llum
      POSTGRES_DB: llum
    ports:
      - "5433:5432"
    volumes:
      - llum_postgres_data:/var/lib/postgresql/data

volumes:
  llum_postgres_data:
